### ISSUE TITLE
TypeError: this.stream.sendRequest is not a function

### ISSUE THREAD

**Issue by ShadowRanger** [SzymonLisowiec/node-epicgames-client#4]
```
Uncaught Promise Error:  TypeError: this.stream.sendRequest is not a function
    at Communicator.sendMessage (C:\TestBot\node_modules\epicgames-client\src\Communicator\index.js:277:15)
    at Communicator.communicator.on (C:\TestBot\index.js:72:26)
    at Communicator.emit (events.js:182:13)
    at Client.stream.on.stanza (C:\TestBot\node_modules\epicgames-client\src\Communicator\index.js:243:13)
    at Client.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:117:30)
    at Client.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\client.js:91:14)
    at Client.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:117:30)
    at WSConnection.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\client.js:341:18)
    at WSConnection.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:128:30)
    at WSConnection.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\transports\websocket.js:86:14)
TypeError: this.stream.sendRequest is not a function
    at Communicator.sendMessage (C:\TestBot\node_modules\epicgames-client\src\Communicator\index.js:277:15)
    at Communicator.communicator.on (C:\TestBot\index.js:72:26)
    at Communicator.emit (events.js:182:13)
    at Client.stream.on.stanza (C:\TestBot\node_modules\epicgames-client\src\Communicator\index.js:243:13)
    at Client.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:117:30)
    at Client.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\client.js:91:14)
    at Client.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:117:30)
    at WSConnection.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\client.js:341:18)
    at WSConnection.prototype.emit (C:\TestBot\node_modules\wildemitter\wildemitter.js:128:30)
    at WSConnection.<anonymous> (C:\TestBot\node_modules\stanza.io\lib\transports\websocket.js:86:14)
```
I am receiving the above error when using the code below:
```
client.egClient = new EpicGamesClient({
	email: "email",
	password: "password"
});

try {
	await client.egClient.init();
	await client.egClient.login();

	const communicator = client.egClient.communicator;

	communicator.on("friend:request", async (data) => {
		communicator.sendMessage(data.account_id, "[Debug 1] This is a test message!");
	});
} catch (error) {
	console.log(error);
}
```

**Comment by SzymonLisowiec** [comment]
Fixed in commit:https://github.com/SzymonLisowiec/node-epicgames-client/commit/7bcb8f6de7e49a0a44447d5ac018eae251005411
